services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend/public:/usr/src/app/public
      - ./frontend/src:/usr/src/app/src
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    volumes:
      - ./backend/bin:/usr/src/app/bin
      - ./backend/routes:/usr/src/app/routes
      - ./backend/app.js:/usr/src/app/app.js
    environment:
      - NODE_ENV=development
      - PORT=5000
  mongo:
    image: mongo:6.0.13
    volumes:
      - mongo-volume:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-volume: