services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend/public:/usr/src/app/public
      - ./frontend/src:/usr/src/app/src
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    volumes:
      - ./backend/src:/usr/src/app/src