services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend/public:/usr/src/app/public
      - ./frontend/src:/usr/src/app/src
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    volumes:
      - ./backend/bin:/usr/src/app/bin
      - ./backend/public:/usr/src/app/public
      - ./backend/routes:/usr/src/app/routes
      - ./backend/views:/usr/src/app/views
      - ./backend/app.js:/usr/src/app/app.js
    environment:
      - NODE_ENV=development
      - PORT=5000